trembita:
  process_definitions:
    - process_definition_id: 'add-lab'
      start_vars:
        - var1
      requires_signature: true

dso:
  url: http://localhost:8081

keycloak:
  url: http://localhost:8082/auth
  realm: test-realm
  client-id: client-id
  client-secret: client-secret

ceph:
  http-endpoint: http://localhost:8083
  access-key: access-key
  secret-key: secret-key
  bucket: bucket

s3:
  config:
    client:
      protocol: http
    options:
      pathStyleAccess: true

bpms:
  url: http://localhost:8084

