server:
  port: 8080

platform:
  security:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState, webServices
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    kafka:
      enabled: false
    kubernetes:
      enabled: false
    webservices:
      readiness:
        services:
          - ${bpms.url}/actuator/health/readiness

spring:
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false