server:
  port: 8080

platform:
  security:
    enabled: false
  logging:
    aspect:
      enabled: false
    primary-url:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState, webServices
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    kafka:
      enabled: false
    kubernetes:
      enabled: false
    webservices:
      readiness:
        services:
          - ${bpms.url}/actuator/health/readiness

spring:
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: false

logbook:
  feign:
    enabled: true
  info-logging:
    enabled: true
  strategy: request-body-on-debug
  exclude:
    - /actuator/**
  obfuscate:
    headers:
      - x-access-token