apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    bpms.url: {{ .Values.bpmsUrl }}
    dso.url: {{ .Values.dsoURL }}
    keycloak.url: {{ template "keycloak.url" . }}/auth
    keycloak.realm: {{ template "keycloak.externalSystemTargetRealm" . }}
    keycloak.client-id: {{ .Values.keycloak.trembitaInvokerClient.clientName }}
    ceph.http-endpoint: https://s3-openshift-storage.{{ .Values.dnsWildcard }}
    spring.zipkin.baseUrl: {{ .Values.zipkinBaseUrl }}